### ISSUE TITLE
Running multiple instances of stream?

### ISSUE THREAD

**Issue by vityafx** [d12i/twitter-stream-rs#5]
Is it okay to run multiple instances of `stream` in different threads with same credentials? I miss tweets sometimes. I use same credentials for the both streams in both threads.

**Comment by d12i** [comment]
Yes, that's possible since the `TwitterStream` is `Send`able. Also, you can use the `futures::stream::Stream::merge` method to handle multiple listeners, which I believe is more efficient and straightforward than having multiple threads.

Note that `TwitterStream` is `!Clone` so you can't simply clone the stream to have multiple instances of listeners. Instead, call the `TwitterStreamBuilder::listen` (or `listen_json`) method multiple times:

```
let builder = TwitterStreamBuilder::user(&token);
let stream1 = builder.listen().unwrap();
let stream2 = builder.listen().unwrap();
```

Of course, running multiple listeners at the same time will increase the chance of being rate-limited.

**Comment by vityafx** [comment]
The question it seems tweets are lost this way. I have two `TwitterJsonStream` in different threads and I log everything. These two twitter streams are connected using same credentials. But it seems that the messages are received only by one thread - other miss that sometimes. I expected both threads to get all tweets but it seems it does not work this way. Am I correct?
